name: Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        shell: bash

        # Don't run scripts to prevent a malicious package from stealing tokens
        # or doing other harmful things.
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm build

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifacts to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
